# Generated by Django 4.1.7 on 2023-03-07 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routine', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(max_length=250)),
                ('task_code', models.CharField(max_length=250)),
                ('task', models.CharField(max_length=250)),
                ('task_answer', models.CharField(max_length=250)),
                ('task_assigned_by', models.CharField(max_length=250)),
                ('task_assigned_to', models.CharField(max_length=250)),
                ('task_status', models.IntegerField()),
            ],
        ),
    ]
