# Generated by Django 4.1.7 on 2023-03-08 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routine', '0002_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='task_description',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
    ]
